### ISSUE TITLE
Panel Transparency Lost in Ubuntu 18.10

### ISSUE THREAD

**Issue by kshitij-agarwal** [Jannomag/Yaru-Colors#1]
After installing all the themes in Ubuntu 18.10, the transparent effect of the panel and topbar was no longer there. It turned to the old black background which was there in 18.04. 

I also compared the file **/etc/alternatives/gdm3.css** of 18.04 and that with 18.10. In 18.10 I the file had the version of 18.04. Reference - [stackoverflow](https://askubuntu.com/questions/1086962/cannot-change-login-screen-background-in-18-10)

**Comment by Jannomag** [comment]
Sorry for the very late response, I wasn't very active since then. 
The solid color of the panel and topbar are given by Yaru's source, not my theme. I didn't change anything on this transparency effect.
