### ISSUE TITLE
Return full color menu items

### ISSUE THREAD

**Issue by maxborowsky** [Jannomag/Yaru-Colors#102]
Return, please, the full color menu items as they appear in the latest original Yaru theme and Yaru Colors 20.10:

![Screenshot from 2021-05-31 16-13-35](https://user-images.githubusercontent.com/20723033/120199414-e1a4fa80-c22b-11eb-926d-547f6df62956.png)
![Screenshot from 2021-05-31 16-20-47](https://user-images.githubusercontent.com/20723033/120199743-406a7400-c22c-11eb-9cbd-ec68ef02111b.png)

In the current version of Yaru Colors, instead, there is now a gray translucent element with a thin color strip on the left:

![screenshot_2021_05_31_1](https://user-images.githubusercontent.com/20723033/120200690-444ac600-c22d-11eb-8b82-c972192d8b0a.png)

And also, please consider the possibility of a Yaru Colors version with colors other than orange by default in the original Yaru theme, but with original purple checkboxes, sliders etc:

![Screenshot from 2021-05-31 16-36-58](https://user-images.githubusercontent.com/20723033/120202717-955bb980-c22f-11eb-9a82-dc21d5500ae7.png)
![Screenshot from 2021-05-31 16-34-51](https://user-images.githubusercontent.com/20723033/120202720-95f45000-c22f-11eb-98e9-e3b2176034df.png)
![Screenshot from 2021-05-31 16-35-34](https://user-images.githubusercontent.com/20723033/120202721-95f45000-c22f-11eb-9533-b1ec0029d2b8.png)

**Comment by lmlorca** [comment]
These changes are in line with upstream.

**Yaru 20.10 (old) vs 21.04 (current)**
![image](https://user-images.githubusercontent.com/29153842/120536683-5e61e100-c3b2-11eb-8058-ec82b61e575e.png)
_(Credit: OMG! Ubuntu!)_

**Comment by Jannomag** [comment]
As @lmlorca said, the changes are part of Yaru 21.04. You could use an older release if you want, I won't change it because Yaru-Colors will stick to Yaru master.
