### ISSUE TITLE
Yaru-Purple-Light for Shell, unreadable text box

### ISSUE THREAD

**Issue by pulver22** [Jannomag/Yaru-Colors#105]
Hi,

I am on Ubuntu 18.04 with Gnome Sheel 3.28.4 . I set up the theme in the title but the text box when typing for looking for an application is totally unreadable. The text is white on white background.

Please, see the image 
![https://i.imgur.com/jhEmn8t.png](https://i.imgur.com/jhEmn8t.png)

**Comment by Jannomag** [comment]
Try on older release. The current one is for 3.38.
