### ISSUE TITLE
White padded border around shell dropdown menù

### ISSUE THREAD

**Issue by pulver22** [Jannomag/Yaru-Colors#106]
OS: Ubuntu 18.04
DE: Gnome Shell 3.28.4

There is a white padding around the notification menù but also any other menù which can be open from a tray icon.

![menu](https://i.imgur.com/BcG7XCb.png)

**Comment by Jannomag** [comment]
Same as https://github.com/Jannomag/Yaru-Colors/issues/105#issuecomment-868405565

**Comment by pulver22** [comment]
I've unfortunately tried all your releases and I couldn't find any working with 18.04. That's a shame because your themes are gorgeous. I guess Gnome changed a lot over the years and it would require a lot of work to you to adjust the theme to an old release. I'll probably stick to another theme for the Shell and use your for the apps and icons.

**Comment by Jannomag** [comment]
Well you could upgrade your gnome version if you like to stick on 18.04.
