### ISSUE TITLE
Icons of GNOME Shell Activities Overview distorted

### ISSUE THREAD

**Issue by regenpfeifer** [Jannomag/Yaru-Colors#108]
Hello,

I installed Yaru-Colors on my computer (Ubuntu 20.04 LTS) with the install script and - unfortunately - chose the option to also modify the GDM3 login screen. After that the icons of the GNOME Shell Activities Overview are distorted: they are not longer in the form of a square, bur compressed horizontally on the left and right sides.

All other icons seem to be faultless (Desktop, Dock). I have created a new user with completely fresh settings and I am seeing this problem with the icons here, too. So this must be a setting on the system, not on the user level, which has been changed.

Can you tell me, which files are changed by the install script of Yaru Colors on system level, when I am granting root permissions to the script?

Thank you very much!

**Comment by Jannomag** [comment]
The gnome shell and gdm3 files should be stored under /usr/share/gnome-shell. There should be a backup as well.

**Comment by regenpfeifer** [comment]
> The gnome shell and gdm3 files should be stored under /usr/share/gnome-shell. There should be a backup as well.

Thank you very much, I could solve the problem with the backup of the file "gnome-shell-theme.gresource".

**Comment by Jannomag** [comment]
Good, im glad you could solve this issue. But I don't know what caused it. Maybe because of the different Gnome version in 20.04.
