### ISSUE TITLE
Classic yaru theme

### ISSUE THREAD

**Issue by Mxrck** [Jannomag/Yaru-Colors#11]
Hi, first of all thanks for your hard work, I really like the old look and feel of yaru (ubuntu 18.10 / 19.04) with flat dark titlebars and menus.

I don't have much experience with the gnome themes so I don't know exactly what I need to look to recover it (I don't like title bar with gradients :( ), there's a possibility you can put me on the right direction or make a yaru classic version?

thanks in advance.

**Comment by Jannomag** [comment]
You could try gtk inspector (easy to Google it). 
With this you'll able to look for the css of every window. 
I'm not planning to add this, because it's already hard work to keep Yaru-Colors updated with the latest version of Yaru, sorry.
