### ISSUE TITLE
Link to Kvantum theme?

### ISSUE THREAD

**Issue by GabePoel** [Jannomag/Yaru-Colors#110]
Heyo! I don't know if this is of interest or not. But, I've [made some Kvantum themes](https://github.com/GabePoel/KvYaru-Colors) to make QT programs fit with Yaru Colors. I was wondering if you could maybe possibly put a link to it in your readme like [Materia](https://github.com/nana-4/materia-theme) does for [Materia KDE](https://github.com/PapirusDevelopmentTeam/materia-kde). It might help with people trying to keep their systems consistent. But, not worries if you'd rather keep the projects more separate.

Thanks a bunch for making Yaru Colors by the way! It's fantastic (hence why I was inspired to make this)! 😊

**Comment by ghostcrafter551** [comment]
Amazing!

**Comment by Jannomag** [comment]
Thanks and done (finally)!
