### ISSUE TITLE
No window border theme MATE - add metacity theme

### ISSUE THREAD

**Issue by FreaxMATE** [Jannomag/Yaru-Colors#113]
Unfortunately Yaru-Colors does not support MATE because of missing metacity themes. The upstream yaru instead gained support for window border theming in MATE (https://github.com/ubuntu/yaru/pull/2540). Would it be possible to add the colored variants of the yaru metacity theme to this project?

**Comment by Jannomag** [comment]
I'll add support for MATE when Yaru added it in the next release. I don't use upstream files because it's too much work for me to keep Yaru-Colors up to date with Yarus frequent changes.

I'm very busy currently and I'll try my best to create a 21.10 release ASAP.
