### ISSUE TITLE
Gnome 40 - Dash to Dock v69 background not transparent but #1d1d1d

### ISSUE THREAD

**Issue by S0llarCode** [Jannomag/Yaru-Colors#115]
Manjaro 21.1.1 Gnome 40.4.0
[with the latest updates] 
Dash to dock (v69) with default Yaru-Orange (or other color) shell theme (yaru-colors-gtk-theme 21.04-1).

Problem : Dash to Dock background not transparent
![before](https://i.ibb.co/qrLY8Ht/issue.png)

Edit file : `/usr/share/themes/Yaru-Orange/gnome-shell/gnome-shell.css`
or your Yaru color theme preference : `/usr/share/themes/Yaru[PREF]/gnome-shell/gnome-shell.css`

edit line 2266: replace `  background: #1d1d1d; ` with `  /*background: #1d1d1d;*/
  background: transparent; `

**Comment by Jannomag** [comment]
Thanks for this hint.

I guess it gets fixed with Yaru 21.10 because it's a Gnome 40 related bug. If so, it'll get fixed with Yaru-Colors as well, when I did a new release for 21.10.

I'll add this as current workaround in the readme.
