### ISSUE TITLE
Latest install on Ubuntu 21.10 (Devel) breaks system. 

### ISSUE THREAD

**Issue by wvhulle** [Jannomag/Yaru-Colors#116]
Gdm3 doesn't start after reboot.

**Comment by Jannomag** [comment]
No support for 21.10, yet. 
I'm very busy at the moment and don't have time to work on Yaru-Colors, currently. Especially for upstream changes by Yaru.
I'll do my best to release Yaru-Colors 21.10 as soon as possible, but it will be AFTER the release of 21.10!

For now, don't use gdm3 theme, GTK and Shell shouldn't be a problem.
