### ISSUE TITLE
GDM3-theme errors on Ubuntu 21.10

### ISSUE THREAD

**Issue by LostinSpacetime** [Jannomag/Yaru-Colors#121]
The install-script fails, since the alternate entry is called gdm-theme.gresource (gdm instead of gdm3). Installing manually applies the theme, but after login, the overview is corrupted. It seems to be some background issue.

**Comment by Jannomag** [comment]
I didn't update for 21.10 yet. I'm very busy at the moment and I didn't even start with the update.

I close this issue because it's version related and not a real bug.

**Comment by hoquangnam45** [comment]
For anyone that need a fix you can run this command: 
```
sudo rm /usr/share/gnome-shell/theme/Yaru/gnome-shell-theme.gresource &&\
sudo cp /usr/share/gnome-shell/theme/Yaru/gnome-shell-theme.gresource.bakup_yarucolors /usr/share/gnome-shell/theme/Yaru/gnome-shell-theme.gresource &&\
sudo update-alternatives --set gdm-theme.gresource /usr/share/gnome-shell/theme/Yaru/gnome-shell-theme.gresource
```

**Comment by cfbastarz** [comment]
> For anyone that need a fix you can run this command:
> 
> ```
> sudo rm /usr/share/gnome-shell/theme/Yaru/gnome-shell-theme.gresource &&\
> sudo cp /usr/share/gnome-shell/theme/Yaru/gnome-shell-theme.gresource.bakup_yarucolors /usr/share/gnome-shell/theme/Yaru/gnome-shell-theme.gresource &&\
> sudo update-alternatives --set gdm-theme.gresource /usr/share/gnome-shell/theme/Yaru/gnome-shell-theme.gresource
> ```
> 
> Then restart, and it should be fixed

It works, thanks @hoquangnam45 !
