### ISSUE TITLE
Missing GTK2 scale-slider.png asset on Dark variants

### ISSUE THREAD

**Issue by koplo199** [Jannomag/Yaru-Colors#122]
Hi,
It looks like there's a missing GTK2 asset for Dark variants of the theme, from the logs :

```
/usr/share/themes/Yaru-Purple-dark/gtk-2.0/main.rc:1140: Unable to locate image file in pixmap_path: "assets/scale-slider.png"
/usr/share/themes/Yaru-Purple-dark/gtk-2.0/main.rc:1141: Background image options specified without filename
/usr/share/themes/Yaru-Purple-dark/gtk-2.0/main.rc:1167: Unable to locate image file in pixmap_path: "assets/scale-slider.png"
/usr/share/themes/Yaru-Purple-dark/gtk-2.0/main.rc:1168: Background image options specified without filename
```
Screenshots illustrating the issue :

![Screenshot from 2021-10-02 16-55-05](https://user-images.githubusercontent.com/85577251/135722105-5f91361f-da39-4c02-9872-2cc8131021fe.png)

Light/Normal variants working as expected : 

![Screenshot from 2021-10-02 16-54-55](https://user-images.githubusercontent.com/85577251/135722116-1c813399-af17-4edb-b22b-d9e19df7dedd.png)

There's also no issue with the disabled/hover version of scale-slider.png, this is especially visible for Qt applications when QT_QPA_PLATFORMTHEME=gtk2 is set, which is (to my knowledge) the only way to make Qt apps to respect the system theme

I checked in the assets folder and indeed scale-slider.png is missing in Dark variants, but as these files are generated I don't know where to make the change to resolve the issue, could you please have a look on this ? Thank you !

**Comment by koplo199** [comment]
Ok I was able to fix it by modifying `assets-dark-fixed.svg` and `dark/gtk-2.0/assets.svg`, in which the scale-slider.png looked odd compared to other entries

I'll attach the .diff of the changes to this comment
[fix_gtk2_scaleslider.diff.txt](https://github.com/Jannomag/Yaru-Colors/files/7272120/fix_gtk2_scaleslider.diff.txt)

**Comment by Jannomag** [comment]
I don't have much time atm.
Can you check this with the latest [Yaru](https://github.com/ubuntu/yaru) source files?

This would help a lot. If their files are wrong, may you open a pull request for Yaru?
