### ISSUE TITLE
Customize more colors

### ISSUE THREAD

**Issue by tvenissat** [Jannomag/Yaru-Colors#13]
Hello! I wanted a version of the Yaru theme that could be recolored to different color schemes so I modified your project to make it work (close enough). Would you be interested in accepting these changes and further modifications? If not, I will make a new repository for those who may want to use it. I wanted to ask you first in case you wanted to collaborate.

Screenshot of Yaru dark:
![yaru-dark-shell](https://user-images.githubusercontent.com/10354465/74093661-9f860180-4a9a-11ea-9c77-e3bceb3d32c0.png)

Screenshot of Yaru dracula dark:
![yaru-dracula-dark-shell](https://user-images.githubusercontent.com/10354465/74093665-a876d300-4a9a-11ea-97b6-6fa62292a9bd.png)

Screenshot of Yaru dracula darker:
![yaru-dracula-darker-shell](https://user-images.githubusercontent.com/10354465/74093667-aad92d00-4a9a-11ea-8d41-190b76d9827f.png)

Here is a snippet of relevant code coming from the `theme-script.sh` file. 

```sh
color_name='dracula'
color_darker_variant='yes'
color_panel_background='1E2029'
color_background_0='282A36'
color_foreground_0='F8F8F2'
color_accent='6272A4'

#calculate black colors
if [ $color_darker_variant == 'yes' ]; then
  color_background_1=$(echo "obase=16;ibase=16;$color_background_0 + 0D0D0D" | bc)
  color_background_2=$(echo "obase=16;ibase=16;$color_background_0 + 2D2D2D" | bc)
  color_background_3=$(echo "obase=16;ibase=16;$color_background_0 + 363636" | bc)
else
  color_background_1=$(echo "obase=16;ibase=16;$color_background_0 + 252525" | bc)
  color_background_2=$(echo "obase=16;ibase=16;$color_background_0 + 454545" | bc)
  color_background_3=$(echo "obase=16;ibase=16;$color_background_0 + 4E4E4E" | bc)
fi

#calculate white colors
color_foreground_1=$(echo "obase=16;ibase=16;$color_foreground_0 - 080808" | bc)
color_foreground_2=$(echo "obase=16;ibase=16;$color_foreground_0 - 333333" | bc)
color_foreground_3=$(echo "obase=16;ibase=16;$color_foreground_0 - 787878" | bc)

#assign utility colors
color_red=$color_accent
color_orange=$color_accent
color_yellow=$color_accent
color_green=$color_accent
color_blue=$color_accent
color_purple=$color_accent
```

The above code calculates the remaining color values for the theme given a background, foreground, and accent color from the user (hard-coded now but could be provided when the user chooses the `custom` option). I basically just calculated the difference in proportions of the default Yaru color values and used them to find the matching colors for the new theme.

Screenshot of Yaru colors:
![yaru-colors](https://user-images.githubusercontent.com/10354465/74093669-ae6cb400-4a9a-11ea-8762-340f4e634eed.png)

Screenshot of Yaru Dracula colors:
![yaru-dracula-colors](https://user-images.githubusercontent.com/10354465/74093707-55e9e680-4a9b-11ea-93da-6e3dc53fa8a7.png)

There is still a lot more work to be done (the gtk theme has not been touched yet, only the shell theme) but I think it can prove useful someday.

**Comment by geckolinux** [comment]
Thanks! This will be useful for me.

**Comment by Jannomag** [comment]
Good idea, but not an issue. You're free to create an own project for free using Yaru-Colors!
