### ISSUE TITLE
Consider Yaru dark grey?

### ISSUE THREAD

**Issue by stevenjaycohen** [Jannomag/Yaru-Colors#14]
If you matched the grey to the surrounding titlebar #3A3A3A would it simply blend in? Would it result in  the close button just looking like an X?

**Comment by Jannomag** [comment]
Maybe, you could try it out by compiling the theme by yourself (using the latest release, until I've updated the 20.04 script to be able to set custom colors).
Go to /src/ and then try ./theme-script.sh Custom
