### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by Leniwcowaty** [Jannomag/Yaru-Colors#142]
I would love to use Yaru for my Fedora install, but well, this doesn't work for GTK4 apps. Are there any plans to update it and enable GTK4 functionality?

**Comment by Jannomag** [comment]
Not on my side, I'm sorry to say this. GTK4 development was a whole new level for me and since I am now a father and not using Ubuntu anymore I stopped working on Yaru-Colors completely. 
@Muqtxdir did the last changes and added GTK4 support with 21.10.
