### ISSUE TITLE
compiling gtk3 custom theme fails

### ISSUE THREAD

**Issue by derVedro** [Jannomag/Yaru-Colors#17]
I tried to compile a custom theme with `theme-script.sh`, but the task ate all of my 24GB ram. The last thing i saw:

> WARNING on line 266, column 15 of /tmp/Yaru-Colors/src/default/gtk-3.20/_headerbar.scss:
> Compound selectors may no longer be extended.
> Consider `@extend *, :link, :selected` instead.
> See http://bit.ly/ExtendCompound for details.

**Comment by Jannomag** [comment]
That looks like an error with the source of Yaru. Which distro and version did you use? 
I've updated everything, so maybe it's fixed for you. I never noticed such an issue.
Please redownload and check again, then report!

**Comment by derVedro** [comment]
that was the last ubuntu 20.04, but I cant reproduce the bug anymore. May be the star were wrong last month but now all compiles nice.
