### ISSUE TITLE
yaru-anycolor

### ISSUE THREAD

**Issue by fkohlgrueber** [Jannomag/Yaru-Colors#19]
I've created the [yaru-anycolor](https://github.com/fkohlgrueber/yaru-anycolor) project which might be of interest for people looking for colored yaru themes for Ubuntu 20.04 / Gnome 3.36. It's early work, but should already work fine in most situations.

As far as I can see, it's approach is quite different than Yaru-Colors'. I'm using a python script to change as little as possible in the official Yaru theme to change its colors. I hope that this reduces maintenance effort in the future. As a bonus, this allows users to easily choose any color they want.

**Comment by Jannomag** [comment]
Looks good, but it's not an issue ;)
