### ISSUE TITLE
Yaru-Colors Orange (to preserve Yaru original)

### ISSUE THREAD

**Issue by geckolinux** [Jannomag/Yaru-Colors#21]
Hi there,

It looks like Yaru for Ubuntu is now moving to a purple highlight tone that a lot of people aren't going to like. Would it be possible to add a Yaru-Colors Orange variant that is basically a copy of the original Yaru scheme from Ubuntu 19.10?

Thanks a lot!

**Comment by Jannomag** [comment]
I've updated the whole theme including an Orange one, I also updated the purple color to a newer, more Ubuntu style one.

**Comment by geckolinux** [comment]
Great, thank you very much!
