### ISSUE TITLE
Several highlights/borders not changed in Ubuntu 20.04

### ISSUE THREAD

**Issue by lostfictions** [Jannomag/Yaru-Colors#23]
Hi there,

Not sure if this is intended/easy to change, but it looks like this theme doesn't change the highlights when an item is active on the top panel:

![image](https://user-images.githubusercontent.com/567041/82158456-fc414700-9855-11ea-8ea7-a9621b06e58a.png)

The Applications tab highlights are also unchanged:

![image](https://user-images.githubusercontent.com/567041/82158484-36124d80-9856-11ea-9026-55fa6965c8ca.png)

And in the Activities overview, the workspace border also remains the default orange:

![image](https://user-images.githubusercontent.com/567041/82158505-57733980-9856-11ea-9ffc-ed99523195a7.png)

This is when installing from commit `89ee264` of this repo using the `Yaru-Blue-Dark` theme. I installed to `~/.local/share/themes`, but had also previously tried installing to `/usr/share/` (until I hit #22) and the highlights were still unchanged.

**Comment by Jannomag** [comment]
Did you set Yaru-Blue-dark also as Gnome-Shell theme? It looks like the stock Yaru shell theme...

**Comment by AshenPaladin** [comment]
I have set the theme as the Gnome-Shell too and I am facing the same issue.

**Comment by Jannomag** [comment]
I fored a push for new files because GitKraken didn't recognized changes in the new and recompiled gnome-shell files. Please check again. 
I tested them a few minutes ago on a freshly installed Ubuntu 20.04 in a VM.

**Comment by lostfictions** [comment]
Thanks for the quick reply! I pulled the latest version of the repo, ran `uninstall.sh` and then `install.sh`, and set the theme. I logged out and back in just to be sure. The highlights are still orange for me, unfortunately:

![Screenshot from 2020-05-23 23-38-15](https://user-images.githubusercontent.com/567041/82745121-9ae61000-9d4e-11ea-8c7d-bfff6cb465fc.png)

If it works on a fresh Ubuntu 20.04 VM, is it possible files from an earlier version of the installer script are interfering somehow?

**Comment by lostfictions** [comment]
Just figured out my issue -- I didn't have the [gnome shell theme extension installed](http://ubuntuhandbook.org/index.php/2017/05/enable-shell-theme-in-gnome-tweak-tool-in-ubuntu/). I'm not familiar with Gnome Shell theming, so I didn't realize this extra step was required. It would be great if there was a note about this in the README!

**Comment by PJSingh5000** [comment]
I can confirm it works fine with User Themes extension enabled.

**Comment by Jannomag** [comment]
I'll add this to readme.md! Issue closed.
