### ISSUE TITLE
checkbox issue

### ISSUE THREAD

**Issue by rodude123** [Jannomag/Yaru-Colors#25]
Hi not sure if this is fixed. I just downloaded the latest commit updated my themes and the checkboxes still are red when checked for some older colours. 
![image](https://user-images.githubusercontent.com/10896262/82232350-6e815c80-9926-11ea-8afa-fe5ed324dbf4.png)
otherwise a great update.
Please let me know if this is going to be fixed. Also, could you make some sort of simple dev guide? I'd like to help with this. Wouldn't mind creating some sort of colour picker so the user can pick there own accent colours

**Comment by Jannomag** [comment]
This is an issue with gtk2 I'm fighting with...it's caused by missing assets in the compiling process. Somehow this happens randomly. I'm currently working on a fix!

**Comment by rodude123** [comment]
Hey, nice release but unfortunately the dark theme still don't work for me don't think it's just green or mate even other colours don't have the checkboxes in dark theme 
![image](https://user-images.githubusercontent.com/10896262/82579784-3415fa80-9b86-11ea-9fc3-eff0dcede587.png)

**Comment by Jannomag** [comment]
I'm about to fix this. I've noticed that those checkbox assets are missing in Yaru's assets.txt, so the rendering script won't render them. I thought I've fixed but I messed it a bit up and mixed two working directories together.Long story short, I'm already rendering everything again. It'll take a few minutes, I'll post here if it's done and uploaded.Sorry!
null

**Comment by rodude123** [comment]
No need to apologize I'm happy that someone out there is doing this. Thank you for this really. I found this while looking. The do not disturb slider seems to have a different colour than the theme. This is a potential issue. Yes I was testing it with Gedit. Thanks again for this. If there is any way I can help please let me know. I would need some sort of documentation on how your code works tho 
![image](https://user-images.githubusercontent.com/10896262/82591955-0639b180-9b98-11ea-8b8c-3abff548ceb7.png)

**Comment by rodude123** [comment]
Just seen the themes are a bit mixed up I think I have different colours for different applications 
![image](https://user-images.githubusercontent.com/10896262/82607530-dfd44000-9bb0-11ea-8578-878ce276e81d.png) don't know how to fix it

**Comment by Jannomag** [comment]
I've updated the gnome-shell themes to fix different colors on some themes. But I need to figure out, what's coloring the Do Not Disturb switch, I couldn't find anything in the .css. But I think I'm able to fix this, soon.

I've also checked the issue with the mixed colors each application - I wasn't able to reproduce it. I tried /usr/ and /home/. Everything looks fine. Some apps need to be restarted or minimized (Brave for example).
![Bildschirmfoto von 2020-05-22 00-27-54](https://user-images.githubusercontent.com/31586674/82612423-1c109c00-9bc3-11ea-8ded-96a3597f2fa2.png)

**Comment by rodude123** [comment]
Great job anyways, don't mind when you fix this, just let me know when you do. Take your time.

**Comment by Jannomag** [comment]
I've redownload my latest commit and tested it on my system and also on a fresh installation of 20.04 in a VM. I can't reproduce this issue. 
Those checkbox assets are present for every color. 
Please try again.

The Do Not Disturb button seems to be either hard coded into Gnome-Shell or hidden very well by the devs. I can't find anything and it's also no part of the gnome-shell.css. 
There's a mention in the `src/shell/gnome-shell-sass/widgets/_messages.scss` for this switch, but it's just for the layout, not witch assets or colors are used.

**Comment by rodude123** [comment]
That's fine I'll just uninstall it and reinstall it I think

**Comment by rodude123** [comment]
just uninstalled and colours don't match up 
![image](https://user-images.githubusercontent.com/10896262/82888008-b31d8100-9f40-11ea-9204-cae93e24229e.png)
I was hoping for a green theme with dark green theme again but it didn't work

**Comment by Jannomag** [comment]
Okay, it should be fixed now...hopefully and finally. Sorry!
Reason: the GTK3.0 themes were compiled wrong because I missed that the 20.04 source has a linked _ubuntu-colors.scss for gtk3.0 (linked to 3.20) instead of using it's own file. I edited my theme-script.sh for this.

**Comment by rodude123** [comment]
don't need to appologize I'm just grateful that someone is doing something like this.

**Comment by rodude123** [comment]
I've not seen an update on github

**Comment by Jannomag** [comment]
There's the commit: 9fc1bf21b3c4f1d4cd203be683c984a33bc65c70

**Comment by rodude123** [comment]
Thanks for this! Really!!!

**Comment by Jannomag** [comment]
No bother, does it work now?

**Comment by rodude123** [comment]
Yes this is it. Thank you for taking the time to fix this. It's these little things that kind of bug me. I wouldn't have been upset if they weren't fixed but I just like that it's been fixed. Ahhhh my life is complete :rofl: lol :joy:

**Comment by Jannomag** [comment]
I'm thinking the same. It's important for me to get things done instead of leaving them unfixed for weeks. I'm glad that everything works. It's a great help to have people for testing.

**Comment by Thyriaen** [comment]
I just downloaded the current master version from the github repository. The theme looks really awesome but the radio-buttons-checked and checkboxes-checked both still appear as a red error ( like in the first screenshot. ). I tried different colors. They all have this error.
