### ISSUE TITLE
Small gap next to dock on Fedora 32

### ISSUE THREAD

**Issue by jlocash** [Jannomag/Yaru-Colors#26]
There appears to be a ~1px gap to the right of the dock on Fedora 32/Gnome 3.36. The default system theme does not have this issue. Affects all theme variants. Installed from master branch as latest release doesn't work on Fedora 32 for me
![1px-gap](https://user-images.githubusercontent.com/40341518/82492756-b930df00-9ab4-11ea-83c6-6553145ca56f.png)

**Comment by Jannomag** [comment]
Did you test stock Yaru? Does this happen even if you resize the dock?

**Comment by jlocash** [comment]
Have not tried stock yaru. I'm not sure if this is a theme issue or a Dash to Dock issue, because this only happens when I have the 'Shrink the dash' option enabled on D2D. When disabled, the gap disappears.

**Comment by Jannomag** [comment]
If I'm correct, Yaru uses its own D2D theme in the Gnome-Shell.css. Maybe this produces the issue, but then it's related to Yaru and not Yaru-Colors. If you like, try Yaru and tell me if it's the same behavior.

**Comment by Jannomag** [comment]
Issue closed, checked on a Fedora VM system. Same issue, it's D2D related.
