### ISSUE TITLE
Every shell theme is still Yaru-Aqua

### ISSUE THREAD

**Issue by AnwarShah** [Jannomag/Yaru-Colors#28]
You latest commit says the issue is fixed. But I've just downloaded the master and installed. The themes are okay, but the shell theme is not. All of theme looks like it's Yaru-Aqua

**Comment by Jannomag** [comment]
So did I, somehow GitKraken messed it up. I've tried to recompile the themes and checked each css for the right colors before I wanted to commit the changes, but GitKraken didn't show any changes. I forced a push with the new compiled files. Please try again.
Sorry for this!

**Comment by AnwarShah** [comment]
@Jannomag Great! Can I have a patch of the last commit? I have a rather slow net, so re-downloading the master is timeconsuming

**Comment by Jannomag** [comment]
Sure, I can send you the files or a link, which color do you want? I can separate the files from the bigger images.
null

**Comment by AnwarShah** [comment]
> Sure, I can send you the files or a link, which color do you want? I can separate the files from the bigger images. null

You can send the orange just for testing. 

btw, I didn't like the new icon theme which shows a chocolate color folder icon like original yaru with just a color touch on the folder folding. The previous icons were great!

**Comment by AnwarShah** [comment]
Yes, I've downloaded somehow. The shell theme is working.

**Comment by AnwarShah** [comment]
But there are some other problems with the shell theme . For example Purple, Purple light doesn't work. only purple dark works

**Comment by Jannomag** [comment]
Strange, I tested it a few minutes ago and couldn't find this issue. I've did a new commit with updated files. Please check again. If it's not working, can you attach a screenshot of your shell including gnome-tweak-tool and also a screenshot of the gnome-shell/assets directory with the gird view of the images?

**Comment by AnwarShah** [comment]
Ok, I'll check and update you

**Comment by Jannomag** [comment]
Is it fixed for you?

**Comment by AnwarShah** [comment]
@Jannomag  Yes, gnome shell theme is fixed

**Comment by Jannomag** [comment]
Great!
