### ISSUE TITLE
Theming breaks for some apps

### ISSUE THREAD

**Issue by lostfictions** [Jannomag/Yaru-Colors#29]
Hi, thanks again for your work on this theme pack. I'm seeing an issue with [Audacious](https://en.wikipedia.org/wiki/Audacious_(software)) in Ubuntu 20.04 -- it seems theming breaks when using any of the Yaru-Colors themes, whereas it works fine with stock Yaru and Yaru-dark themes.

Yaru:
![Screenshot from 2020-05-23 23-54-44](https://user-images.githubusercontent.com/567041/82745314-e5688c00-9d50-11ea-9a53-94fbcbd1ad40.png)

Yaru-dark:
![Screenshot from 2020-05-23 23-55-03](https://user-images.githubusercontent.com/567041/82745317-eac5d680-9d50-11ea-9b11-b640a1ee4831.png)

Yaru-Blue:
![Screenshot from 2020-05-23 23-56-04](https://user-images.githubusercontent.com/567041/82745338-09c46880-9d51-11ea-87fa-0b34d2da2b03.png)

Yaru-Blue-dark:
![Screenshot from 2020-05-23 23-56-19](https://user-images.githubusercontent.com/567041/82745343-1a74de80-9d51-11ea-9d5a-22121dbba67f.png)

As you can see, the stock Yaru themes seem to work fine, but the Yaru-Colors themes seem to not be applied at all (except for icons and window decorations) and the application seems to be using a (pretty ugly) fallback.

This is Audacious 3.10.1, which is the default version offered by the Ubuntu 20.04 software repositories. According to [the Wikipedia page for Audacious](https://en.wikipedia.org/wiki/Audacious_(software)), this version is using GTK2, so I wonder if it might be an issue that applies to all GTK2 apps.

**Comment by Jannomag** [comment]
That's strange. I tested my themes with A Widget Factory. 
Where did you install the themes?
If it's ~/.local/share/themes, please try ~/.themes/.
If that doesn't work, too, please try /usr/share/themes (just for testing).
I'll try to figure it out!

**Comment by lostfictions** [comment]
Uninstalling and reinstalling to `~/.themes` seems to have fixed it! Though this time I got a warning about symlinking:

```
#? 2
Please enter your theme path [/home/me/.local/share/themes]: 
/home/me/.themes
Copying Yaru-Blue to /home/me/.themes...
ln: failed to create symbolic link '/home/me/.themes/Yaru-Blue-dark/gtk-3.0/assets': File exists
ln: failed to create symbolic link '/home/me/.themes/Yaru-Blue-dark/gtk-3.20/assets': File exists
```

**Comment by Jannomag** [comment]
Oh, that's no problem, it just says that the files are already present. I've just forgotten to edit the install.sh to remove the symlinks, because they're not needed anymore. Thanks for this, I'll fox this.
null

**Comment by Jannomag** [comment]
Issue closed, I've updated the install.sh!
