### ISSUE TITLE
Color of file icons for desktop not consistent with others.

### ISSUE THREAD

**Issue by gapplef** [Jannomag/Yaru-Colors#3]
Color of file icon for desktop not consistent with others, is this intended?
![Screenshot](https://user-images.githubusercontent.com/5604665/65824598-6ba20080-e29e-11e9-98d0-4816999bee4b.png)

**Comment by Jannomag** [comment]
The icons are based on original Yaru icons. I just changed the base colors of the orange-only icons to fit to the colors of each theme. The desktop icon looked strange when I tried to change the orange color so I leaved it as it is.
