### ISSUE TITLE
Gnome Shell Switch Buttons are Purple

### ISSUE THREAD

**Issue by PJSingh5000** [Jannomag/Yaru-Colors#30]
With the User Themes extension enabled, and a Yaru Colors theme selected, the switch button widgets still use the aubergine (purple) color.

Please see the "Do Not Disturb" switch in this screenshot...

![Gnome Shell Switch Button](https://user-images.githubusercontent.com/19394936/82765509-82750480-9de5-11ea-949b-940ed6a3e6d0.png)

**Comment by Jannomag** [comment]
That's not the Gnome-Shell itself. It's an extension built into the 3.36. I was trying to find this but couldn't find anything. I'll close this issue, because it's not Yaru-Colors related, sorry.

**Comment by AndreaPasqualini** [comment]
The same issue happens with the accessibility pop-up that appears whenever you have an accessibility option turned on. For me, this is Large Text. As far as I know, this pop-up has been there for much longer than the "do not disturb" switch and suggests there may be something up with your themes.

![purple-switch-cropped](https://user-images.githubusercontent.com/24243677/84565237-53541200-ad57-11ea-94a3-1db2ab91accd.png)

**Comment by Jannomag** [comment]
I tried to find those buttons for days. Maybe it's some kind of extension with hard coded or compiled color schemes. 
The assets of Gnome-Shell are in the right colors and in the gnome-shell.css there isn't any code for those switched.

**Comment by AndreaPasqualini** [comment]
I understand. Would it be worth to open an issue (if one is not present already) over at [Yaru's main repo](https://github.com/ubuntu/yaru)? Those guys did manage to put purple in that place. The team at [Pop OS](https://github.com/pop-os/gtk-theme) did change that color (I think it's with orange). The reference files come directly from Gnome's Adwaita. Therefore, those guys should know how to change that color. If you forked Yaru's repo (which you did), then there must be something up with _their_ files.

**Comment by Jannomag** [comment]
Maybe...
BUT I think I've found something...I'll try it out and edit this post or reply. I don't know when, but it shouldn't take that much time!

**Comment by kjellarneodegaard** [comment]
For those looking for what Jannomag found, check out the awesome [Yaru-Colors](https://github.com/Jannomag/Yaru-Colors). Also on snap
