### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rodude123** [Jannomag/Yaru-Colors#31]
I would love to help with this project and would be nice if there was some wiki page or something which documents what you have done so far. If this can be don then that would be a great help to maintian this too.
Thank you.

**Comment by Jannomag** [comment]
Oof, that would be more work than creating this...
Just read my comments in the scripts.
Basically I didn't do anything but creating a script containing all steps and scripts from stock Yaru which are needed to compile the themes.

The theme-script.sh is the main actor creating the themes. I tried to comment nearly everything to understand how it works. You just need a bit of batch knowledge. 
The python script in `src/` are copied directly from stock Yaru, just like the directory tree of `src/`.

**Comment by rodude123** [comment]
> Oof, that would be more work than creating this...
> Just read my comments in the scripts.
> Basically I didn't do anything but creating a script containing all steps and scripts from stock Yaru which are needed to compile the themes.
> 
> The theme-script.sh is the main actor creating the themes. I tried to comment nearly everything to understand how it works. You just need a bit of batch knowledge.
> The python script in `src/` are copied directly from stock Yaru, just like the directory tree of `src/`.
> 
> If you want to contribute, try to understand my theme-script.sh, than it should be easy. If you have any questions, feel free to contact me directly via email.
> 
> Issue closed, a wiki is too much work for this, sorry.

Yea no worries, I'll just read that then.
Cool
