### ISSUE TITLE
no folders' icons on desktop && opacity of toolbar.

### ISSUE THREAD

**Issue by olczaq** [Jannomag/Yaru-Colors#35]
With all the settings in Gnome-Tweak you can see here:

[
![yaru_issues](https://user-images.githubusercontent.com/18404628/84434755-8481f480-ac28-11ea-9d31-f6d6aa861553.png)
](url)

1. There are no folders' icons on the desktop
2. The toolbar od terminal (as well as for example image viewer) is completely transparent.

Installed manually in ~/.themes, Ubuntu 20.04.

**Comment by Jannomag** [comment]
Can you try to move the theme to ~/.local/share/themes and reset it with gnome tweak tool?
What are the file types of the files with the missing icons? Yaru-Color inherits to stock Yaru icon pack (at least it should). Do you have stock Yaru installed?

**Comment by olczaq** [comment]
Moved to ~/.local/share/themes gave the same result. The missing icons on the desktop are folders, they appear with Yaru icons but not with Yaru-deepblue. How to check if stock Yaru is installed? Personally, I will stick back to default Yaru-dark mode. Anyway, nice work.
