### ISSUE TITLE
Maybe fix for Gnome-Shell Switch buttons being Purple

### ISSUE THREAD

**Issue by Muqtxdir** [Jannomag/Yaru-Colors#38]
Hi,
The gnome-shell theme is still using the standard **Yaru**'s purple color for switches (toggles) even though the ***.svg(s)*** are differently colored for various **Yaru-colors** themes. 
- Changing the url of **background-image: url("resource:///org/gnome/shell/theme/toggle-on.svg");** to **background-image: url("toggle-on.svg");** Simply Changing the url of background-image under **.toggle-switch:checked** in ***gnome-shell.css*** kinda works for me. 
(I think maybe it has something to do with ***_colors.scss***  in src files `/shell/gnome-shell-sass`)

- Maybe this helps for issues in #30, #25 

![to](https://user-images.githubusercontent.com/54065734/85221937-7cb71280-b3d5-11ea-803b-26f3e88e6d6e.png)

**Screenshot after url-change**

![Screenshot from 2020-06-21 15-41-40](https://user-images.githubusercontent.com/54065734/85221984-d91a3200-b3d5-11ea-81e7-755a9e13f2b8.png)

Thanks! Hope someone finds this useful

**Comment by Jannomag** [comment]
Thanks! I've already found this out a few days ago but wasn't able to test it. When I have the time I'll update the themes.

**Comment by Jannomag** [comment]
Updated repo with this! 
Themes are updated, as well as the theme-script.sh.
Thanks again for this!

**Comment by Muqtxdir** [comment]
Noice!
