### ISSUE TITLE
Missing color changes in some colors

### ISSUE THREAD

**Issue by a-yildiz** [Jannomag/Yaru-Colors#43]
It looks like for some of the themes, the switch colors in Gnome Shell Extensions are not correct.

Correct implementation (e.g. Amber): 
![Screenshot from 2020-07-13 09-52-12](https://user-images.githubusercontent.com/24276393/87331501-e74c0180-c4ee-11ea-89f3-6914b8a575e9.png)

Incorrect implementation (e.g. Red):
![Screenshot from 2020-07-13 09-52-42](https://user-images.githubusercontent.com/24276393/87331639-267a5280-c4ef-11ea-819f-1f80080ce75a.png)

Notice how the switches of "Turbo Boost" and "Auto Switch" default to the original purple color of Yaru. I think you might have simply forgotten to modify them for certain colors.

I am loving this theme, and would really appreciate if you could fix this :)

**Comment by Jannomag** [comment]
aw dammit...I know I've must have forgotten something...
I've fixed it, current release file is updated.

I'll close this issue! Thanks for the hint!
