### ISSUE TITLE
Ubuntu Software (Snap store?) still light themed

### ISSUE THREAD

**Issue by BLovegrove** [Jannomag/Yaru-Colors#45]
Hi there,

First off - appreciate this to no end. Would be awesome if this was included in ubuntu by default.
Secondly, one small problem: The software store remains light themed even in the custom dark themes. I've tried it with all the dark themes so far and all have the same result. Screenshots for example/

Normal dark theme:
![image](https://user-images.githubusercontent.com/32378871/87869108-2dbec600-c9f1-11ea-8982-6369f379f0a3.png)

Yaru-purple-dark theme:
![image](https://user-images.githubusercontent.com/32378871/87869145-99a12e80-c9f1-11ea-9c39-d31ef95038ea.png)

Don't make issue reports on here often so let me know if there's anything else needed.

**Comment by Jannomag** [comment]
This is a snap issue. Snap uses its own theme resources which are write protected. I wasn't able to create a Yaru-Colors snap package, yet and I don't know if I'll add this ad all. 
It's snaps fault and not a bug with Yaru-Colors.
What you're seeing here isn't a light theme, it's Adwaita, the stock gnome theme.

Two options for you:
1. Change the theme with GTK Inspector manually to Yaru-Dark, but this will reset everytime you're logoff.
2. Completely remove the snap garbage and install everything from repos or packages - there are some tutorials on the WWW for this. I did it like this and my Ubuntu is free of this snap mess.

Issue closed, I'll add a note to the readme (I thought I've done it but I didn't somehow...).

**Comment by BLovegrove** [comment]
Thanks for the advice!
Goodbye Snap I guess.
