### ISSUE TITLE
Terminal tabs not in right color

### ISSUE THREAD

**Issue by sciencyboi** [Jannomag/Yaru-Colors#46]
terminal tabs are fully black and not going with the theme
![image](https://user-images.githubusercontent.com/59108967/88235360-56b4b480-cc98-11ea-9bd5-9e2196c2b554.png)

Using Yaru-Blue-dark on ubuntu 20.04. (specifying becuase ive manually changed the color of close button - and nothing else)
Thanks for your efforts, @Jannomag  :)

**Comment by Jannomag** [comment]
I can't test it at the moment but I think it has something to do with the terminal settings. There's a setting for using system colors or so. Take a look at this, please. I think it fix this. Otherwise I don't know why this is black since Yaru-Colors uses the same source as Yaru but I'll try to work on a fix, if I can relate this bug.

**Comment by sciencyboi** [comment]
> I can't test it at the moment but I think it has something to do with the terminal settings. There's a setting for using system colors or so. Take a look at this, please. I think it fix this. Otherwise I don't know why this is black since Yaru-Colors uses the same source as Yaru but I'll try to work on a fix, if I can relate this bug.

I tried switching to system colors and it did not fix it.
I tried matching the terminal settings in css to original Yaru css, and it indeed seems okay. I will try meanwhile, to add some extra parameters to try and alter the terminal tab color.

**Comment by Jannomag** [comment]
Sorry for the late reply.
I've tried it on my own installation and on a freshly installed vm as well but can't relate this issue with the latest release. Here's a screenshot how it looks on my system using Yaru-Blue-dark located in ~/.themes:
![Bildschirmfoto von 2020-07-27 18-55-15](https://user-images.githubusercontent.com/31586674/88569489-c92be880-d03a-11ea-81aa-92e72e8a5bdf.png)

**Comment by Jannomag** [comment]
I'll close this issue, for now. Please reply if you've found a fix or any hint
