### ISSUE TITLE
Ubuntu Software app becomes complete transparent

### ISSUE THREAD

**Issue by ShrirajHegde** [Jannomag/Yaru-Colors#48]
On applying any color from yaru-colors ubuntu software turns completely transparent with 0% opacity.

To recreate, install with the provided script as root and select any color (dark/light) in gnome tweaks.

![Here is the Screenshot](https://user-images.githubusercontent.com/66936172/88486695-37ba6900-cf9d-11ea-8039-2fad8e675498.png)

**Comment by Jannomag** [comment]
This is a common issue using third party themes with snap applications. So it's not Yaru-Colors related, it's a Snap issue.
I've added this to the readme ("known bugs" at the bottom) including workarounds.

Issue closed.
