### ISSUE TITLE
Custom colors?

### ISSUE THREAD

**Issue by hermanndetz** [Jannomag/Yaru-Colors#5]
Great work!

Is there an easy way to rebuild the theme with a custom color or is this something that would need to be done manually on each file?

**Comment by Jannomag** [comment]
Sorry for the late response, I didn't have the time...
It's possible with the scripts I've created for creating Yaru-Colors. I'll release them soon as source for this git.

**Comment by Jannomag** [comment]
Closing this issue. I added the possibility to enter custom colors in my src/theme-script.sh script.
