### ISSUE TITLE
Radio & Checkbox buttons - "checked" - red error

### ISSUE THREAD

**Issue by Thyriaen** [Jannomag/Yaru-Colors#51]
I just installed the theme and i love it, however i installed the latest commit and the issue of the missing checkboxes still persist ( at least for me ).

I tried different colors ( purple and red ). Both have the issue

![Screenshot from 2020-08-18 16-45-49](https://user-images.githubusercontent.com/10978280/90528272-bb1d4380-e172-11ea-9193-e6e77f4c973c.png)

**Comment by Thyriaen** [comment]
My mistake, if i download the repository it does not work, however if i download the release and use the theme in there it works. I'll not delete my comment and just close the issue for someone else to stumble upon this.

**Comment by Jannomag** [comment]
So, cloning the repo causes the issue while downloading the release does not?
That's strange. I don't have much time at the moment, but when I do, I'll look over it.

**Comment by Thyriaen** [comment]
Well, i don't know if they are linked correctly, to mee it seems like it
![directories](https://user-images.githubusercontent.com/10978280/90986798-cb278f80-e585-11ea-92bd-e95ee3145b2f.png)
Here are the contents of my directories

**Comment by Jannomag** [comment]
The symbolic links looking good. 
You listed the files in the assets directory of Gnome-Shell ... I need to know the contents of gtk-3.20/assets, gtk-3.0/assets and gtk-2.0/assets.
You can print the output to a file by using '>' and then paste the content or attach the file.

**Comment by Thyriaen** [comment]
Okey, here ya go

[2.txt](https://github.com/Jannomag/Yaru-Colors/files/5114795/2.txt)
[3.2.txt](https://github.com/Jannomag/Yaru-Colors/files/5114796/3.2.txt)
[3.txt](https://github.com/Jannomag/Yaru-Colors/files/5114797/3.txt)

**Comment by Jannomag** [comment]
Gtk-2.0 looks good. But the other two are just symbolic link paths. Please go to Yaru-Purple and not Yaru-Purple-dark and redo the ls command.

**Comment by Thyriaen** [comment]
When i extract Yaru-Purple aswell - the checkboxes are now fixed - is this initended that both Yaru-Purple and Yaru-Purple-dark are needed for it to work ? 

Do you still want the contents of the assets ?

**Comment by Jannomag** [comment]
That explains it. 
Stock Yaru is build like this, so you have to extract the whole color with every flavor. The asset files are all the same for each flavor, so there's no need for having them in each, it's saves space and time (also spacetime maybe...jk).
When you use the install.sh, it does exactly this. 
Btw, this is also common for other themes.

Issue closed.
