### ISSUE TITLE
Default integration in Ubuntu 

### ISSUE THREAD

**Issue by EndrII** [Jannomag/Yaru-Colors#52]
Nice work.
Is there a default integration planned in Ubuntu so that the theme can be changed from the gnome-settings in the "Appearance" section?

**Comment by Jannomag** [comment]
Not yet and I don't even know if the Ubuntu devs took note about Yaru-Cors. I would like it if it's integrated with a color chooser for example, just in the same menu where you can choose between dark, light and default. 

I'll close this issue because I don't have any plans to do it at the moment.
