### ISSUE TITLE
[Fix] Arch GNOME Panel Icons : humanity-icon-theme

### ISSUE THREAD

**Issue by tur1ngb0x** [Jannomag/Yaru-Colors#55]
**Information**
Distro: Arch GNOME 2020.09.01
GNOME Shell: 3.36.5
GNOME Extensions: User Themes, Desktop Icons NG

**Description**
Yaru-Colors icon theme fails to apply on the gnome panel.

**Steps to reproduce**
1. `git clone https://github.com/Jannomag/Yaru-Colors.git`
2. `cd Yaru-Colors`
3. `./install`
4. Open GNOME Tweak Tool, apply any Yaru-Color icon pack.
5. Restart GNOME Shell / Restart Session / Restart Machine.

**Expected Behaviour**
GNOME panel icons should show applied Yaru icon pack.

**Actual Behaviour**
GNOME panel icons still show up as Adwaita icon pack.

**Fix**
1. Install humanity-icon-theme (dependency)
    * Debian/Ubuntu (should be installed by default): `sudo apt install humanity-icon-theme`
    * Arch/Manjaro: `sudo yay -S humanity-icon-theme`
2. Open GNOME Tweak Tool, apply any Yaru-Color icon pack.
3. Restart GNOME Shell.
4. GNOME panel icons will now show applied Yaru icon pack.

**Comment by Jannomag** [comment]
Thanks for this, I added this to the readme.md.
