### ISSUE TITLE
Gnome terminal

### ISSUE THREAD

**Issue by druid-rift** [Jannomag/Yaru-Colors#56]
The gnome-terminal is not rendering properly and the only way to fix this issue is to use a different terminal or change the theme.

**Comment by NovaViper** [comment]
Im having the same issue as well, on Manjaro Gnome 20.1

**Comment by Jannomag** [comment]
Is the gnome terminal a snap application? If so, that's the issue. If not, I'll try to figure it out but it'll take time since I don't have much of it at the moment.

**Comment by NovaViper** [comment]
> Is the gnome terminal a snap application? If so, that's the issue. If not, I'll try to figure it out but it'll take time since I don't have much of it at the moment.

It's not a snap app, but comes from the official manjaro repo.

**Comment by Jannomag** [comment]
Do you have a screenshot?

**Comment by NovaViper** [comment]
Here ya go
![Screenshot from 2020-10-03 11-16-22](https://user-images.githubusercontent.com/7191115/94996364-f54b7480-0569-11eb-8b5f-e60bc41b6b13.png)

**Comment by Jannomag** [comment]
Strange. I don't have this, at least I didn't noticed it. I'm not able to test it at the moment but I remember an entry in the terminal settings to enable or disable the system theme (don't remember the correct naming for this).
Can you try this at tell me if this works?Since I just used Yaru's source I don't know what's the issue there. But I'll try to figure it out when I've the time.

**Comment by NovaViper** [comment]
That's what I enabled, the use system theme settings under the color category. The issue only occurs when I enable that setting, otherwise it doesn't

**Comment by Jannomag** [comment]
Hi again.
I checked it on 20.04 and 20.10, both freshly installed and didn't have this issue at all.
Can you check it with my latest commit again, please?

**Comment by NovaViper** [comment]
> Hi again.
> I checked it on 20.04 and 20.10, both freshly installed and didn't have this issue at all.
> Can you check it with my latest commit again, please?

Oh hey, I actually just switched to Budgie, Gnome was making my computer act up. So im gonna close this issue. Thanks though! :)

**Comment by Jannomag** [comment]
Alright.
