### ISSUE TITLE
nemo filemanager

### ISSUE THREAD

**Issue by maheer-kolcha** [Jannomag/Yaru-Colors#58]
text selection is not working in nemo while renaming file

**Comment by Jannomag** [comment]
Are you using Cinnamon? This can be the issue because cinnamon isn't supported, yet. Does stock Yaru work for you?

**Comment by maheer-kolcha** [comment]
no, all yaru based theme has same problem

**Comment by Jannomag** [comment]
Then I can't fix it because I'm using Yaru as source. Please open an issue at Yaru. If they fixed it, Yaru-Colors will do as well.

Issue closed.
