### ISSUE TITLE
Installer doesn't propose Amber theme color

### ISSUE THREAD

**Issue by mmatela** [Jannomag/Yaru-Colors#59]
The propositions look like this:
````
Okay, which color do you want to install?
1) Aqua        3) Brown      5) Green      7) MATE       9) Purple    11) Red       13) Yellow
2) Blue        4) Deepblue   6) Grey       8) Pink      10) Orange    12) Teal
````

It seems the first element in the `colors` list in the `install.sh` script is ignored.
When I switched Amber with Aqua in that list, I could install Amber, but Aqua was missing.

Actually, something else must be missing too, because there are 14 colors listed for the `colors` variable.

I also noticed in a later section of the script `# setting color codes variables:` the Amber string is used in two cases.

**Comment by mmatela** [comment]
> Actually, something else must be missing too, because there are 14 colors listed for the colors variable.

Never mind, I thought 12 is the last element, but there's 13.

**Comment by Jannomag** [comment]
Issue fixed?
If not can you post the line numbers, please? I'm currently on my mobile phone mainly and it's hard to view and search the whole script on the small display.

**Comment by mmatela** [comment]
Oh, sorry - didn't get the notification from github.
All except that one sentence is still relevant.

Currently the `colors` list is in line 175 and amber duplication in line 735.
