### ISSUE TITLE
snap apps still not themed

### ISSUE THREAD

**Issue by fouzan14** [Jannomag/Yaru-Colors#61]
I use fair amount snap applications and there is no Yaru-colors for snap

now, that there is support for snap-theme in apps (refer this: https://discourse.ubuntu.com/t/a-quick-update-on-our-progress-on-automatic-theme-installation-for-snaps/18633 and https://www.omgubuntu.co.uk/2020/06/change-snap-app-theme)

So can you make the snap-package? and solve this transparent issue with Ubuntu-software
![snap-boi](https://user-images.githubusercontent.com/69529058/96706951-ddbb1b00-13b4-11eb-93cc-cd0aeaa6006c.png)

please solve this issue

**Comment by Jannomag** [comment]
I took note of this but didn't found the time to try it out. It'll be a part of the next Yaru 20.10 release update, I think. 

I leave this issue open as reminder.

**Comment by Jannomag** [comment]
So I'm trying to find out how snap works and how I can build a snap package using my theme files.
But either it's too complicated for me or I'm just to stupid...I don't get it. 
This will eat hours over hours and I didn't make any progress for the last few hours.

Therefore I leave this issue open as a call for help...

Sorry that I can't figure it out, yet.

**Comment by Muqtxdir** [comment]
hi @Jannomag,

I was recently able to bundle [Yaru-remix](https://github.com/Muqtxdir/yaru-remix) theme for snap apps (See this: https://snapcraft.io/yaru-remix-themes)
If you want I can help you with creating the snap for **Yaru-colors**, although I know very little about snap-packaging

**Comment by Jannomag** [comment]
I saw this and looked at your git for the yaml file. Your theme is getting compiled by snap. I don't want it to compile because they're too many themes and I would need to create extra scripts for this.

I wanted to add just the built files from ./Themes and ./Icons to be in the snap.

**Comment by Muqtxdir** [comment]
You can add your `install.sh` to the yaml instead of compiling the whole theme

I think in yaml find you should point `install.sh` to snap theme directories

**Comment by Muqtxdir** [comment]
specify `./install.sh --themes` to copy all the desired theme-files to a location
specify `./install.sh --icons` to copy all the desired theme-files to a location

this is a snapcraft.yaml file if you add `--themes` and `--icons` to `install.sh`:

```bash
name: yaru-colors
version: "20.04.5"
base: core18
architectures:
  - all
summary: Yaru-remix GTK and icon themes
description: |
  A snap that exports the Yaru-colors GTK and icon themes.

grade: stable
confinement: strict

slots:
  gtk-2-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/Yaru-Amber
        - $SNAP/share/themes/Yaru-Amber-light
        - $SNAP/share/themes/Yaru-Amber-dark
        - $SNAP/share/themes/Yaru-Aqua
        - $SNAP/share/themes/Yaru-Aqua-light
        - $SNAP/share/themes/Yaru-Aqua-dark
        - $SNAP/share/themes/Yaru-Blue
        - $SNAP/share/themes/Yaru-Blue-light
        - $SNAP/share/themes/Yaru-Blue-dark
        - $SNAP/share/themes/Yaru-Brown
        - $SNAP/share/themes/Yaru-Brown-light
        - $SNAP/share/themes/Yaru-Brown-dark
        - $SNAP/share/themes/Yaru-Deepblue
        - $SNAP/share/themes/Yaru-Deepblue-light
        - $SNAP/share/themes/Yaru-Deepblue-dark
        - $SNAP/share/themes/Yaru-Green
        - $SNAP/share/themes/Yaru-Green-light
        - $SNAP/share/themes/Yaru-Green-dark
        - $SNAP/share/themes/Yaru-Grey
        - $SNAP/share/themes/Yaru-Grey-light
        - $SNAP/share/themes/Yaru-Grey-dark
        - $SNAP/share/themes/Yaru-MATE
        - $SNAP/share/themes/Yaru-MATE-light
        - $SNAP/share/themes/Yaru-MATE-dark
        - $SNAP/share/themes/Yaru-Orange
        - $SNAP/share/themes/Yaru-Orange-light
        - $SNAP/share/themes/Yaru-Orange-dark
        - $SNAP/share/themes/Yaru-Pink
        - $SNAP/share/themes/Yaru-Pink-light
        - $SNAP/share/themes/Yaru-Pink-dark
        - $SNAP/share/themes/Yaru-Purple
        - $SNAP/share/themes/Yaru-Purple-light
        - $SNAP/share/themes/Yaru-Purple-dark
        - $SNAP/share/themes/Yaru-Red
        - $SNAP/share/themes/Yaru-Red-light
        - $SNAP/share/themes/Yaru-Red-dark
        - $SNAP/share/themes/Yaru-Teal
        - $SNAP/share/themes/Yaru-Teal-light
        - $SNAP/share/themes/Yaru-Teal-dark
        - $SNAP/share/themes/Yaru-Yellow
        - $SNAP/share/themes/Yaru-Yellow-light
        - $SNAP/share/themes/Yaru-Yellow-dark

        
  gtk-3-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/Yaru-Amber
        - $SNAP/share/themes/Yaru-Amber-light
        - $SNAP/share/themes/Yaru-Amber-dark
        - $SNAP/share/themes/Yaru-Aqua
        - $SNAP/share/themes/Yaru-Aqua-light
        - $SNAP/share/themes/Yaru-Aqua-dark
        - $SNAP/share/themes/Yaru-Blue
        - $SNAP/share/themes/Yaru-Blue-light
        - $SNAP/share/themes/Yaru-Blue-dark
        - $SNAP/share/themes/Yaru-Brown
        - $SNAP/share/themes/Yaru-Brown-light
        - $SNAP/share/themes/Yaru-Brown-dark
        - $SNAP/share/themes/Yaru-Deepblue
        - $SNAP/share/themes/Yaru-Deepblue-light
        - $SNAP/share/themes/Yaru-Deepblue-dark
        - $SNAP/share/themes/Yaru-Green
        - $SNAP/share/themes/Yaru-Green-light
        - $SNAP/share/themes/Yaru-Green-dark
        - $SNAP/share/themes/Yaru-Grey
        - $SNAP/share/themes/Yaru-Grey-light
        - $SNAP/share/themes/Yaru-Grey-dark
        - $SNAP/share/themes/Yaru-MATE
        - $SNAP/share/themes/Yaru-MATE-light
        - $SNAP/share/themes/Yaru-MATE-dark
        - $SNAP/share/themes/Yaru-Orange
        - $SNAP/share/themes/Yaru-Orange-light
        - $SNAP/share/themes/Yaru-Orange-dark
        - $SNAP/share/themes/Yaru-Pink
        - $SNAP/share/themes/Yaru-Pink-light
        - $SNAP/share/themes/Yaru-Pink-dark
        - $SNAP/share/themes/Yaru-Purple
        - $SNAP/share/themes/Yaru-Purple-light
        - $SNAP/share/themes/Yaru-Purple-dark
        - $SNAP/share/themes/Yaru-Red
        - $SNAP/share/themes/Yaru-Red-light
        - $SNAP/share/themes/Yaru-Red-dark
        - $SNAP/share/themes/Yaru-Teal
        - $SNAP/share/themes/Yaru-Teal-light
        - $SNAP/share/themes/Yaru-Teal-dark
        - $SNAP/share/themes/Yaru-Yellow
        - $SNAP/share/themes/Yaru-Yellow-light
        - $SNAP/share/themes/Yaru-Yellow-dark
        
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/Yaru-Amber
        - $SNAP/share/icons/Yaru-Aqua
        - $SNAP/share/icons/Yaru-Blue
        - $SNAP/share/icons/Yaru-Brown
        - $SNAP/share/icons/Yaru-Deepblue
        - $SNAP/share/icons/Yaru-Green
        - $SNAP/share/icons/Yaru-Grey
        - $SNAP/share/icons/Yaru-MATE
        - $SNAP/share/icons/Yaru-Orange
        - $SNAP/share/icons/Yaru-Pink
        - $SNAP/share/icons/Yaru-Purple
        - $SNAP/share/icons/Yaru-Red
        - $SNAP/share/icons/Yaru-Teal
        - $SNAP/share/icons/Yaru-Yellow
        

parts: 
  theme:
    after: [utils]
    plugin: nil
    source: https://github.com/Jannomag/Yaru-colors.git
    source-type: git
    source-tag: 20.04.6
    build-packages:
      - sassc
      - libcanberra-gtk-module 
      - libglib2.0-dev
    override-build: |
        snapcraftctl build
        mkdir -p $SNAPCRAFT_PART_INSTALL/share/themes
        ./install.sh --themes $SNAPCRAFT_PART_INSTALL/share/themes
        $SNAPCRAFT_STAGE/split-gtk-theme.sh $SNAPCRAFT_PART_INSTALL
        mkdir -p $SNAPCRAFT_PART_INSTALL/share/icons
        ./install.sh --icons $SNAPCRAFT_PART_INSTALL/share/icons
        $SNAPCRAFT_STAGE/update-icon-cache.sh $SNAPCRAFT_PART_INSTALL/share/icons
    stage:
      - share/gtk2/*/gtk-2.0
      - share/themes/*/gtk-3*
      - share/icons/Yaru-*

  utils:
    plugin: dump
    source: utils
    prime:
      - -*
    build-packages:
      - try: [gtk-update-icon-cache]
      - else: [libgtk-3-bin]
```

**Comment by Jannomag** [comment]
Thanks!
But I have another question:
If I add those options to the script which path do I need to specify?
I can't figure out how snap knows where those files are when they were copied by the script.

**Comment by Muqtxdir** [comment]
like add the option `./install.sh --themes` option to make user specify the destination from terminal
for ex: `./install.sh --themes /usr/share/themes`
so in **snapcraft.yaml** I added, `./install.sh --themes $SNAPCRAFT_PART_INSTALL/share/themes`

**Comment by Jannomag** [comment]
Ahh now I understand...dammit. 
I'll try it when I find some time (little daughter at home is not very good for hobbies)

**Comment by Muqtxdir** [comment]
> I'll try it when I find some time (little daughter at home is not very good for hobbies)

sure, take your time

**Comment by Jannomag** [comment]
I'm currently trying to get it to work with your yaml file.
But I get this message:
`Failed to pull source: unable to determine source type of 'utils'.`
Do you have an idea? I didn't find anything...

**Comment by Muqtxdir** [comment]
I got the same error when I tried it on Ubuntu 20.10, so I tried it on Ubuntu 20.04 and I didn't come across that error

try building it on Ubuntu 20.04

**Comment by Jannomag** [comment]
I did a fresh 20.10 install on my desktop and noticed that snap works with virtual drives now while on my laptop, installed 20.10 a few days ago, it doesn't. I'll try it there...

**Comment by Muqtxdir** [comment]
@Jannomag, I forgot to tell you change **source-tag** to **source-commit:** add the latest commit here (133b9a596dc1d9b5fdd450b44d4e42bcde62915b)

**Comment by Jannomag** [comment]
I removed this line for testing.
It seems to work with my latest commit. It's currently in devmode and I'll release it soon.
Thanks for your help @Muqtxdir

**Comment by Muqtxdir** [comment]
>Thanks for your help @Muqtxdir

Glad that I could help you.

@Jannomag can your share the .snap file? my email: muqtadir5555@gmail.com

**Comment by Jannomag** [comment]
Issue closed.
Release of the snap package will be there soon.
