### ISSUE TITLE
Can't install with script

### ISSUE THREAD

**Issue by luuluuu** [Jannomag/Yaru-Colors#62]
I've tried to install full-pack themes with install.sh and have a problem:
`/home/l/Yaru-Colors-master/install.sh: 62: [[: not found`
`-e You ran this script as root, default install path is set to`
`'/usr/share/themes' and '/usr/share/icons' which can also be changed later!`
`/home/l/Yaru-Colors-master/install.sh: 92: Syntax error: "do" unexpected (expecting "}")`

so i've tried to do it with install_OLD.sh and have fail again:
`-e Version 20.04.4`
`-e `
`/home/l/Yaru-Colors-master/install_OLD.sh: 67: Syntax error: "do" unexpected (expecting "fi")`

Ubuntu 20.04.1 (from mini.iso) + Unity (ubuntu-unity-desktop)

**Comment by Jannomag** [comment]
How do you execute the install.sh?
What does `/bin/bash --version` say?

**Comment by luuluuu** [comment]
> How do you execute the install.sh?
`sh '/home/l/Загрузки/Yaru-Colors-master/install.sh' `
or
`sudo sh '/home/l/Загрузки/Yaru-Colors-master/install.sh' `
the same result

> What does `/bin/bash --version` say?
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.

**Comment by Jannomag** [comment]
Move into your directory with cd and execute the install.sh using ./install.sh.Using sh as command will run the script as she'll script and ignores the #!/bin/bash direction at the beginning of the file. Bash is needed for most commands in the script.
-------- Ursprüngliche Nachricht --------Von: luuluuu <notifications@github.com> Datum: 22.10.20  09:02  (GMT+01:00) An: Jannomag/Yaru-Colors <Yaru-Colors@noreply.github.com> Cc: Jan Schröder <jannomag@gmx.de>, Comment <comment@noreply.github.com> Betreff: Re: [Jannomag/Yaru-Colors] Can't install with script (#62) 



How do you execute the install.sh?

sh '/home/l/Загрузки/Yaru-Colors-master/install.sh' 

or

sudo sh '/home/l/Загрузки/Yaru-Colors-master/install.sh' 

the same result





What does /bin/bash --version say?

GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

Copyright (C) 2019 Free Software Foundation, Inc.

**Comment by luuluuu** [comment]
> Move into your directory with cd and execute the install.sh using ./install.sh.Using sh as command will run the script as she'll script and ignores the #!/bin/bash direction at the beginning of the file. Bash is needed for most commands in the script. 

that's works! Thank you

**Comment by Jannomag** [comment]
Great, issue closed.
