### ISSUE TITLE
Mention explicitly that Yaru-Colors depends on humanity, yaru and hicolor icon packs

### ISSUE THREAD

**Issue by tur1ngb0x** [Jannomag/Yaru-Colors#63]
Referencing my previous issue : https://github.com/Jannomag/Yaru-Colors/issues/55

On some distros without the following packages - humanity, yaru and hicolor icon packs, Yaru Colors icon pack may fail to apply. It needs installation of extra packages to render properly on Debian/Ubuntu/Arch based distros.

**Fix**
1. Install dependencies
    * Debian/Ubuntu: `sudo apt install humanity-icon-theme yaru-theme-icon hicolor-icon-theme`
    * Arch/Manjaro: `yay -S humanity-icon-theme yaru-icon-theme hicolor-icon-theme`
2. Apply any Yaru-Color icon pack.
3. Restart GNOME Shell / Cinnamon Shell.
4. Panel icons will now show applied Yaru-Color icon pack.

**Comment by Jannomag** [comment]
Thanks and sorry that I didn't do this already. 
I added your lines to the readme.md. thanks for this hint.
