### ISSUE TITLE
No focus indicator for checkboxes and radio buttons

### ISSUE THREAD

**Issue by mmatela** [Jannomag/Yaru-Colors#65]
Is it just me, or do the checkboxes and radiobuttons look exactly the same whether they have focus or not? It's a big problem when operating without a mouse.
I'm using the grey color.

**Comment by Jannomag** [comment]
I didn't notice this, yet but I'll check it.
Does it happen everywhere or just in some applications?

**Comment by Jannomag** [comment]
I tried it on my 20.10 installation as well on a freshly installed 20.10 VM. I didn't notice this in Nautilus.

**Comment by Jannomag** [comment]
Issue closed due to no response
