### ISSUE TITLE
Primary colors to Nord

### ISSUE THREAD

**Issue by luX0r-reload** [Jannomag/Yaru-Colors#66]
Hi, it's just an idea but I'd like to see how Yaru Colors theme looks using primary Nord color for background windows, title bars, borders, etc.
Hope U have time to have it a try.

**Comment by Jannomag** [comment]
Which color scheme do you mean exactly?
Do you have a source or color codes?

New ideas are always welcome

**Comment by luX0r-reload** [comment]
Just the Nord color scheme. I think it applied to Yaru theme.
This is the Nord color scheme:

https://github.com/arcticicestudio/nord

**Comment by Jannomag** [comment]
So you mean a complete redesign including titlevar and such?

That's a nice idea and when I have the time for it I'll try it out...maybe I create a completely new theme, called Yaru-Nord.

**Comment by luX0r-reload** [comment]
Yes, it is! Yaru-Nord is a beautiful name.

**Comment by Jannomag** [comment]
It's a very nice idea as well. I'll try to keep it in mind but it will take time since the work is very time I'm consuming.I will leave this issue open as reminder.Thanks for the suggestion

**Comment by Jannomag** [comment]
I tried it during my works on 21.04 release. It's very much work to do and I can't afford the time for it, sorry.
