### ISSUE TITLE
Not working on 20.10

### ISSUE THREAD

**Issue by vescovaccio** [Jannomag/Yaru-Colors#67]
Tried to install using the snap method. Option doesn't appear in Nautilus right click menu.

**Comment by Jannomag** [comment]
Which option do you mean?
The snap package just adds support for snap apps, you still need to indtl the theme locally

**Comment by vescovaccio** [comment]
Sorry, my bad. Was trying to install Folder Colors Yaru in 20.10, since there ppa for Groovy isn't there. I think I am confusing Folder Colors, Yaru Theme, and Integration with Snap apps. I guess this is simply the latter part. I already have the Yaru theme, and I thought the Yaru-Colors snap installed both the colour options for the theme and the right menu folder color selector in Nautilus, but I gather now that they are separate components. I'm having trouble installing Folder Colors separately, but I'll try and work it out. Thanks!

**Comment by Jannomag** [comment]
Okay then, glad it's working now!
