### ISSUE TITLE
Red Squares for Radio Buttons

### ISSUE THREAD

**Issue by somejavadev** [Jannomag/Yaru-Colors#68]
Hi,

First off thank you very much for this project. I want to enquire if the theme is working correctly on my Ubuntu 20.04LTS.

If you have a look at the screenshot below:

![Selection_013](https://user-images.githubusercontent.com/6507120/99234526-4ef7bd80-27fd-11eb-8c1f-d8218e38a175.png)

I am not sure if the bright red squares are correct or should be there? This is on the light-teal theme. I would also expect the red to be teal.

If you look closely there are red squares for round radio buttons. This specific screenshot is on the File manager preferences and is also visible in the gedit preferences screen.

System details:

![image](https://user-images.githubusercontent.com/6507120/99234836-be6dad00-27fd-11eb-9307-bdf16a1d7798.png)

This is on both the last 20.04 release and the 20.10 release of yaru-colors.

**Comment by Jannomag** [comment]
Did you put all three Yaru-Teal directories in your theme directory? It's mandatory, it looks like you're just using Yaru-Teal-light

**Comment by somejavadev** [comment]
@Jannomag, thanks for the reply that has solved it!

**Comment by Jannomag** [comment]
I added this to the readme
