### ISSUE TITLE
Weekdays in the calendar widget are not the right color

### ISSUE THREAD

**Issue by sn0wm3** [Jannomag/Yaru-Colors#69]
After turning off all my other extensions, cloning the repo and running install.sh on Ubuntu Focal Fossa, my calendar widget looks like this

![calendar](https://user-images.githubusercontent.com/17390859/99350889-68d0e900-286d-11eb-87c8-68e52c2c5103.png)

(description: a screenshot of the GNOME calendar widget with the yaru-dark-pink shell theme. the weekdays on the calendar are dark and blend in with the background) 

I had an older version of the dark shell theme installed, and i had played around with the CSS to make my toasts white while keeping everything else dark, but i deleted it and reinstalled it because radios and check-boxes were turning into red squares. is anyone able to replicate this on their machine?

**Comment by Muqtxdir** [comment]
hi @sn0wm3;

maybe it's because you are using the latest version of Yaru-colors (v20.10 is based on Ubuntu 20.10)

try using the theme from **20.04.6** release (suggesting this because you are currently using Ubuntu 20.04)


```
# to switch to 20.04.6snap release:

git clone https://github.com/Jannomag/Yaru-colors.git
cd Yaru-Colors 
git checkout tags/20.04.6snap

```

**Comment by Jannomag** [comment]
Check Out what @Muqtxdir said. I didn't notice this but I'll check it out.

**Comment by Jannomag** [comment]
Issue closed due to no response
