### ISSUE TITLE
Full accent color

### ISSUE THREAD

**Issue by federicofavale** [Jannomag/Yaru-Colors#7]
Hi, I'm basically copying my comment from gnome-look.org. I didn't realice github would be a better place for this suggestion :)

--

What do you think of (since this is a modified version of the original Yaru theme) making progress bars, checkboxs, scrollbars, etc. respect the theme "accent color"?

It just seems a little odd choosing -lets say- the red version and getting blue sliders or green checkboxes :)

I don't know if anyone who uses this theme (or even you) would agree with me, but I just wanted to add this into consideration.

Greetings!

**Comment by federicofavale** [comment]
I see all images are png, I though they would be svg. 
That would add much more effort to this suggestion... anyway, I think this won't be possible after all but I leave that to you to decide :)

**Comment by Jannomag** [comment]
It's possible, the source is SVG which gets rendered to PNG. I already thought about this idea but I wanted to keep the Yaru style. Maybe I'll release a new flavor of Yaru-Colors...but it doubles the amount of work - and I need a new Name.

**Comment by Jannomag** [comment]
If you want to test and help contact me via e-mail. I'll close this issue, now.
