### ISSUE TITLE
PURPLE Color should be used, not ORANGE(Base) Color

### ISSUE THREAD

**Issue by robinzt** [Jannomag/Yaru-Colors#70]
In the file "src/theme-script.sh", according the comment: 
>  #Addition for 20.04 - new purple color is $aubergine = #924D8B!

purple color  #924D8B should be replaced by "$purple_col". 
But the actual code is using "$base_col":
> sed -i -e "s/924D8B/$base_col/g" $source32_path/_palette.scss

It should be "**$purple_col"**:
> sed -i -e "s/924D8B/$purple_col/g" $source32_path/_palette.scss

So I patched the "src/theme-script.sh".

[use_purple_color.patch.zip](https://github.com/Jannomag/Yaru-Colors/files/5557614/use_purple_color.patch.zip)

**Comment by Jannomag** [comment]
Thanks for this, can you please make a pull request for this? It's much easier.
Also, which lines do you mean exactly?

**Comment by robinzt** [comment]
Please see #71 

The line numbers are: 605, 709, 944

**Comment by Jannomag** [comment]
Thanks - merged and issue closed!
