### ISSUE TITLE
yaru 1.0 colours for 20.04

### ISSUE THREAD

**Issue by meetdilip** [Jannomag/Yaru-Colors#72]
Hi, It was very refreshing when `yaru 1.0` debuted with Orange and Green instead of Orange and Purple we have now in `20.04`. Can you please tell me how to modify one of the colour packs with `yaru 1.0` Orange and Green ? 

I chose `Amber` but when I search through Adobe Brackets for the colour change, `Find and Replace` says there is no entry for #8c5e11 which is listed as Secondary colour in Amber colour scheme. I was able to use  `Find and Replace` through Adobe Brackets and change Amber Primary - #eea834 to Ubuntu Orange. It would be great if I can at least change the top-right dropdown menu seek bar colour to Green if not all. 

All of us really appreciate the hard work you are attaching to the default theme and are happy that this project exists. Thanks

**Comment by Jannomag** [comment]
Well, I don't modify the .css files. They're getting created using the sassc command and the scss files.
The colors are changed in _palette.scss.
During this process, the primary colors gets variated by sassc into different color shades. So, you could try to search for all colors (there are websites which can extract colors from css files).
But I don't understand what you mean exactly...
Which colors bother you?

**Comment by meetdilip** [comment]
Thanks for the reply. Currently, the default Yaru theme has **Ubuntu Orange and Purple**. Can you help me prepare a version which is `Ubuntu Orange and Green` ( which was the colour in yaru theme for 18.04 ).

**Comment by meetdilip** [comment]
Something like this @Jannomag  ?

![1 0](https://user-images.githubusercontent.com/6965443/99910936-12edbc80-2d17-11eb-90a9-d31b0e0723d5.png)

**Comment by Jannomag** [comment]
Ah okay.
You can clone this repo and compile the theme using my theme-script.sh.
For this you need some dependencies, which will be shown if not installed. Important: you need Inkscape 0.92.4! Try to install this version, it's complicated. Or use an 19.04 vm.    
    
Then, go to /src/default/gtk-3.20/ and open the _palette.scss file. Replace the color for aubergine (#924D8B) with your desired green color (should be the same as green in this file).    
Then head back to /src/ and run the theme-script.sh like this:    
```./theme-script.sh Orange --noicons```    
This will start the compiling process for Orange without rendering icons and cursors (this would take long). 
The script won't ask you anything. If done, the files are located in /src/_compiled/

Dependencies needed, if I remember correctly:
- optipng
- libcanberra-gtk3-module
- libcanberra-gtk-module
- Inkscape (0.92.4!)
- sass
- sassc
- python2.7
- python-pil

**Comment by meetdilip** [comment]
Hi, I tried to set up a build environment. Sadly not able to do so with my hardware. Can I trouble you with a request ? If possible, can you build a theme option with the attached `_palette.scss`

[_palette.zip](https://github.com/Jannomag/Yaru-Colors/files/5600769/_palette.zip)

Thanks

**Comment by Jannomag** [comment]
like this?
[Yaru-Orange.zip](https://github.com/Jannomag/Yaru-Colors/files/5608112/Yaru-Orange.zip)
