### ISSUE TITLE
Purple stays

### ISSUE THREAD

**Issue by meetdilip** [Jannomag/Yaru-Colors#73]
I am currently using Aqua for GTK as well as Shell theme. Everything is good and beautiful other than the fact that some apps like Inkscape still has Purple in it even when the GTK inspector shows Aqua. Please see

![Screenshot from 2020-11-23 09-19-21](https://user-images.githubusercontent.com/6965443/99928262-558eb380-2d6e-11eb-8daf-48d90e8053f3.png)

Inkscape was installed using PPA. It would be nice to know how to replace the Purple with the theme colour, or a different colour. Thanks.

**Comment by Jannomag** [comment]
Are you sure you installed the PPA package and not the snap?

**Comment by meetdilip** [comment]
Yes, I checked. There is an entry in software settings for PPA dev/stable, something like that.

**Comment by Jannomag** [comment]
It looks like snap. Can you please enter following command:    
```which inkscape```    
If the output is like `/usr/bin/inkscape` you're correct, if it's in `/snap/[...]` then you installed the snap application.

**Comment by meetdilip** [comment]
Hi,

```
$ which inkscape
/usr/bin/inkscape
```
I installed it yesterday. Had shutdown and restarted a few times during that period. The theme is in Home > .themes

Thanks

**Comment by Jannomag** [comment]
Just for trying:Place your themes in ~/.local/share/themes (create if it doesn't exists).The relogin.

**Comment by meetdilip** [comment]
Placed Yaru-Blue in .local > share > themes . Tried shutdown and restart

![Screenshot from 2020-11-23 14-09-39](https://user-images.githubusercontent.com/6965443/99942474-bb426600-2d95-11eb-8369-db9c79befbd2.png)

**Comment by meetdilip** [comment]
A small update. Inkscape is not honouring system theme and reverting to Yaru / last selected theme on restart. ie, we will have to manually choose System Theme or our preferred theme. Setting the theme as " System Theme "  is not working.

The good part is, when we change it manually, Purple goes away. Thanks.

**Comment by Jannomag** [comment]
Im sorry to say that this might be an Inkscape related issue. Please open an issue on their git (I think they're on gitlab). Or try to contect the devs or write a post on reddit.
I believe it has something to do with Inkscapes GTK2 theme usage, but I really don't know.

I leave this issue open for a few days, if you find a solution using a way I mentioned before, feel free to post it here!

**Comment by meetdilip** [comment]
@Jannomag , please see

https://gitlab.com/inkscape/inbox/-/issues/4078

**Comment by Jannomag** [comment]
As I read it there it's an application issue.
I close this issue, sorry - I can't help with this.

**Comment by meetdilip** [comment]
Thanks for attending.
