### ISSUE TITLE
Install as flatpak theme

### ISSUE THREAD

**Issue by johannesjh** [Jannomag/Yaru-Colors#76]
Feature Request: It would be awesome if installing a yaru-colors theme would also install the theme for flatpak apps, in order for these apps to have the same appearance as .deb-packaged apps.

Background/Motivation: I installed the yaru colors theme and I am very happy with the results. Unfortunately, apps installed via flatpak have a different appearance. Judging from this article https://www.linuxuprising.com/2018/05/how-to-get-flatpak-apps-to-use-correct.html, the fix would be to install the theme for flatpak apps.

**Comment by Jannomag** [comment]
I was thinking about this but didn't have the time to figure out how flatpak works, yet. Snap was hard enough for me...I was sitting there for 3 days without any results until I got help from a other user.

I will leave this issue open, maybe I find time and motivation over Christmas. So, I can't promise anything.

**Comment by johannesjh** [comment]
thank you very much for your consideration!

**Comment by tosziro** [comment]
Guys you can force flatpak to use your custom theme by this command
`sudo flatpak override --filesystem=~/.themes`

**Comment by johannesjh** [comment]
Thank you for the hint! A more secure version of this would probably include a read-only flag, as follows:

```
sudo flatpak override --filesystem=~/.themes:ro
```

I gave it a quick try but it does not seem to work for me. 
...I probably need to try some more.

@tosziro have you found the command to be effective?
Does it require restarts or re-installations for the command to have any effect?

**Comment by Mek101** [comment]
Currently, I've personally already submitted [Matcha](https://github.com/vinceliuice/Matcha-gtk-theme/) for approval. I can try and package Yaru-Colors, but I'm going to need @johannesjh permission to publish them on flathub

**Comment by Muqtxdir** [comment]
@Mek101, it would be better for @Jannomag if you link the flathub PR in your comment above there, that way he can have a look at your work

**Comment by Mek101** [comment]
Given that Yanu Colors has a total of a wopping 45 possible combinations, I don't operate directly on the manifests, but I use a python script to generate them from a template

Here's the script: https://gitlab.com/Mek101/flatpak-theme-updater

Here's the template: https://gitlab.com/Mek101/flatpak-theme-presets/-/blob/master/Yaru-Colors/templates/manifest.template

If you want to inspect the generated manifests download the script (the development branch has the Yaru-Colors templates as the time of writing), `cd` into the directory, then run `./theme_update.sh Yaru-Colors -p`, to generate each repo in the `repos` directory

**Comment by Mek101** [comment]
> @Mek101, it would be better for @Jannomag if you link the flathub PR in your comment above there, that way he can have a look at your work

I pinged the wrong username, ops :P

**Comment by Mek101** [comment]
ping @Jannomag

**Comment by Jannomag** [comment]
@Mek101 Tha ja for the script. I’m very busy and can’t work on Yaru-Colors at the moment. I‘ll look at it when I have the time for YC again. 21.04 needs updates as well.

I did most of the things at work but my boss decided to give us more work than usual, so I need to find time at home 😩

**Comment by Mek101** [comment]
Well, if you're ok with it, I can package and submit the themes myself, then mantain and keep them up to date

**Comment by Jannomag** [comment]
Sure, you mean just the flatpak, then maintain it when I released updates?

**Comment by Mek101** [comment]
Precisely. I will make and submit the manifests for the current version, then update them when you release a new one, and so on

**Comment by Jannomag** [comment]
This would help a lot, thanks. If you like you can send me the links to the packages so i can add them to the Readme and Gnome-Look Page.

**Comment by Mek101** [comment]
The packages are hosted as @flathub repositories. As of now, they don't exist yet. I will ping you as soon as they're all published.
(Plus flatpak themes don't require manual installing and don't have a store page; the `flapak` command installs them automatically basing off the currently set theme)

**Comment by Muqtxdir** [comment]
Just fetched the runtimes from **flathub** and I must say absolutely great work @Mek101 for getting this on **flathub.org**. Really appreciate you doing this :smiley:

**Comment by Mek101** [comment]
You welcome :+1:

**Comment by Mek101** [comment]
@Jannomag all packaged and published 👍

**Comment by Jannomag** [comment]
Awesome, thanks (nice birthday present 😂)
