### ISSUE TITLE
How to use this theme in Ubuntu mate? Possível? 

### ISSUE THREAD

**Issue by Daniel-usr** [Jannomag/Yaru-Colors#8]
How to use this theme in Ubuntu mate desktop? I can not

**Comment by rodude123** [comment]
Ubuntu mate uses the mate desktop environment so this is not possible. This is made for gnome desktop environement

**Comment by Jannomag** [comment]
Correct.
I didn't create a Mate theme, because it's a very handy and time consuming work. If stock Yaru supports it, I'm able to add this to Yaru-Cors, as well
