### ISSUE TITLE
Timeshift is not in dark and often this installer fails to copy themes and icons

### ISSUE THREAD

**Issue by HritwikSinghal** [Jannomag/Yaru-Colors#80]
After enabling yaru-brown-dark or any dark color, some apps like timeshift are still in light color. But timeshift is dark on Yaru-dark. so maybe setting fallback theme for dark theme to yaru-dark may work.

and many times (on clean install) of ubuntu 20.04 or 20.10, this installer will run and no matter what options i select, it will fail to copy themes and icons to the respective dirs.

let me know if you need any more info.

**Comment by Jannomag** [comment]
Did you install Yaru-Brown as well and not just Yaru-Brown-dark only?

**Comment by HritwikSinghal** [comment]
i installed all the themes that were present, but most of the time i had to manually copy them to ```~/.themes``` and ```~/.icons``` folder since this would fail to do.

**Comment by sanwablo** [comment]
The same happens with Zotero. 

Could this be because it is the snap version?

Would installing the themes in `/usr/share/themes` solve this issue?

**Comment by HritwikSinghal** [comment]
@sanwablo No, my app is native linux app and not snap or flatpak. Snaps dont follow system themes so no normal theme will work for snaps. You need separate themes for snaps . A quick web search will give you results for that.

@Jannomag any updates?

**Comment by Jannomag** [comment]
Sorry for the late reply. I don’t have any updates because I’m quite busy at the moment, sorry for this.

**Comment by maydayv7** [comment]
The themes must be copied to `/usr/share/themes`, as Timeshift runs as root. You could try symlinking the directories if you do not want to copy the themes to the root directory.

**Comment by ChaosBlades** [comment]
Yep...
`sudo cp -r ~/.themes/Yaru-Red-dark/ /usr/share/themes/`
resolved the issue.
