### ISSUE TITLE
Will yaru-colors support gnome 40?

### ISSUE THREAD

**Issue by fouzan14** [Jannomag/Yaru-Colors#82]
I've just come to know that ubuntu 21.04 won't use Gnome 40 and stick to the Gnome 3.38 release. However, I use Fedora and really appreciate your work and was wondering whether you'd make yaru-colors theme ready for Gnome 40 this March?

**Comment by fouzan14** [comment]
FYI, Yaru has decided to theme what's in Ubuntu 21.04
See this issue: [#2553](https://github.com/ubuntu/yaru/issues/2553)

**Comment by Jannomag** [comment]
Sorry for the late reply.

of course I’ll try to add 40 support, but I don’t know when I find the time for it and how complicated the new theme engine is.
I ask need to wait until Yaru is released for Gnome 40. 

I close this issue.
