### ISSUE TITLE
Prompt text box is not changed

### ISSUE THREAD

**Issue by WHK102** [Jannomag/Yaru-Colors#83]
By example, when mount a external disk with licks password shows the popup asking the password, the input border focus use the default color and not from the theme.

**Comment by Jannomag** [comment]
Do you have a screenshot? I couldn’t reproduce it. Maybe you didn’t activate the shell theme?

**Comment by WHK102** [comment]
Yes, https://ibb.co/cgZTwF5 i use Yaru-Teal: https://ibb.co/jfkDWCh

Use a stick usb, create a encrypted partition using lucks from gnome disks, now extract usb and put again, you can see the password prompt with orange border input.

**Comment by Jannomag** [comment]
Sorry for the ultra late reply.

You need to enable the shell theme, too. For this follow the instructions in the readme file, you need to install the User Themes shell extension first.
