### ISSUE TITLE
Feature request - Support for change the default pink login color

### ISSUE THREAD

**Issue by WHK102** [Jannomag/Yaru-Colors#84]
Please, add support for change the default login color, like as https://github.com/WHK102/gnome-shell-3-helper

**Comment by ahvth** [comment]
This is now a feature in the latest commit. If you download the theme via `git clone` and run `install.sh`, you will be given the opportunity to also update the gdm theme :blush:

**Comment by Jannomag** [comment]
I added this feature weeks ago. It’s not very easy to implement this, but I got it working.
