### ISSUE TITLE
Where does snap installs Yaru-colors pack?

### ISSUE THREAD

**Issue by UltraBurstXD** [Jannomag/Yaru-Colors#85]
I'm having trouble to set up the theme downloaded via snap store (Ubuntu). They don't appear on gnome tweaks. Can someone tell me where they have been kept?

**Comment by sanwablo** [comment]
You need to activate the snap theme via Terminal. The instructions are on the Software center.

Run the following command after installing the snap theme (and also after installing any new snap software): 

`for i in $(snap connections | grep gtk-common-themes:gtk-3-themes | awk '{print $2}'); do sudo snap connect $i yaru-colors:gtk-3-themes; done && for i in $(snap connections | grep gtk-common-themes:gtk-2-themes | awk '{print $2}'); do sudo snap connect $i yaru-colors:gtk-2-themes; done && for i in $(snap connections | grep gtk-common-themes:icon-themes | awk '{print $2}'); do sudo snap connect $i yaru-colors:icon-themes; done`

**Comment by Muqtxdir** [comment]
hi @UltraBurstXD,

The [yaru-colors-snap](https://snapcraft.io/yaru-colors) is for apps that are packaged as snap ex: **Ubuntu-software** (to fix these issues: #61, #48, #45, #37, #27, #20). That means to apply the themes sysytem-wide you still need to manually install it under the specified themes and icons directories

> Can someone tell me where they have been kept?

the snap-package contents are placed under `/snap/yaru-colors/current/share`

**Comment by UltraBurstXD** [comment]
Ohh... I get it. Thanks for answering.
