### ISSUE TITLE
Issue with active states on checkboxes and radio buttons.

### ISSUE THREAD

**Issue by thoughtspacewebsites** [Jannomag/Yaru-Colors#86]
Hey, so I managed to clone down the repo and read through your theme-script.sh script to get a general idea of how things function. Using that, I modified all the colors in the color section under the "Green" attributes to hex codes that I preferred (my user icon background on Github here). I then ran "./theme-script.sh Green" to regenerate the corresponding green files. I opted to enable and compile for all available platforms just for posterity (GTK2, GTK3, and Unity), and icons. I took the resulting theme and icons folders that were created in the _compiled folder, and copied them to /usr/share/themes, and /usr/share/icons, respectively. Afterwards, I activated the theme through Gnome Tweaks for shell and application theme, as well as icons and cursor. Everything looks mostly good, with the exception of the active states on radio buttons and checkboxes. They just display a bright red square. Any idea what might be going on here? I've attached a screenshot as an example of what I'm seeing.
![Screenshot from 2021-03-02 11-52-41](https://user-images.githubusercontent.com/2941602/109684815-a58bcc00-7b4e-11eb-884f-4ef1b1a866e1.png)

**Comment by ahvth** [comment]
Hi, please make sure you're compiling all versions of the theme for all platforms, meaning light, dark, and "classic". See this snippet from the main readme.md known bugs section:

```
Red checkboxes (mostly nautilus)
Install the whole color, not just dark or light.
So your theme directory has to contain (for example) the directories:
Yaru-Blue, Yaru-Blue-dark, Yaru-Blue-light.
Reason: to save space and work the needed asset files are in the default directory only and symlinked from light/dark to default.
```

**Comment by Jannomag** [comment]
Just as @ahvth said: install every variant for the desired colors. Then it should work. The missing assets are contained in the default variant and used by light and dark.

**Comment by thoughtspacewebsites** [comment]
Well that solved the problem but now all my inputs are just grey instead of my green. If I use the light variant, they're all green as expected, but when using the dark variant, they just show grey. I'm also noticing a lot of file not found issues when compiling cursors, and I notice one as the script starts too, but all the files it says aren't available actually are there, and permissions are correct.

**Comment by thoughtspacewebsites** [comment]
Ok, so the red checkboxes issues was totally fixed how you guys mentioned, copying all theme files. My bad for not reading the note at the very bottom of the README. I did, however, still have an issue where any attempts to use the dark theme that was generated had a lot of grey areas that should have been green. After digging and poking some, and making sure I got my dependencies just right (That Inkscape version really matters!) I managed to discover that there seemed to be two missing symlinks for generating the dark theme variants. I just made a pull request which adds them. Testing on my end verifies this works as expected!

**Comment by Jannomag** [comment]
Glad you find the solution for you issues.

the Inkscape Version really matters and it’s hard to get a pre 1.0 version anywhere.
I was struggling with this for two days. I don’t know if Yaru devs already fixed it, because the issue is Inkscape related.
Inkscape 1.0 has other commands than 0.98x, which is really stupid.
