### ISSUE TITLE
New color theme

### ISSUE THREAD

**Issue by Maritsu** [Jannomag/Yaru-Colors#87]
This is pretty much issue #66, except it's an idea for adding Nord as a variant of Yaru-colors instead of a whole new theme

**Comment by Jannomag** [comment]
Nord is complex, I need to recollect everything. I already tried it once but there where several bugs. Due the lack of time I stopped it (for now). 

I will try to keep it mind but I can’t promise it. Maybe someone else puts time and effort into a Nord theme using my source files.
