### ISSUE TITLE
Can't select Yellow color in install script

### ISSUE THREAD

**Issue by bulletpal** [Jannomag/Yaru-Colors#89]
I believe there is a bug that prevents the color yellow from being selected in the install script. A sure way to replicate this bug is to run install.sh with root privileges and do the following:

Do you want to install the complete package? -> yes
Is this correct? -> yes
Please enter your theme path -> default
Please enter your icon path -> default
Do you want to enable themes, icons and other stuff? -> yes
Do you want to enable a theme, if yes, which variant? -> normal
Okay, which color should it be? -> Yellow
Incorrect input, please enter a number from the list!

Line 134 contains the code,
`if [ 1 -le "$REPLY" ] && [ "$REPLY" -le $(($#-1)) ]; then`
It is in the package_color_menu() function. Changing it to
`if [ 1 -le "$REPLY" ] && [ "$REPLY" -le $(($#)) ]; then`
fixed the issue for me. Line 146 in the icon_color_menu() function is exactly the same, so it probably has the same issue as well. 

Yellow is probably not a popular color, so it's probably not that important haha

**Comment by Jannomag** [comment]
Sorry for the late reply!
I’ll check this when I find some time but I’m quiet busy atm

**Comment by Jannomag** [comment]
Fixed with upcoming 21.04 release.
