### ISSUE TITLE
Add Muffin XFWM and Marco support 

### ISSUE THREAD

**Issue by sergioad** [Jannomag/Yaru-Colors#91]
Hello friends, I love Yary and I remembered this theme would have a teal option, ideal for Manjaro, but when I installed it I saw it had not decorations for neither Cinnamon nor XFCE, could you add them please ?

**Comment by Jannomag** [comment]
Sorry for the late reply. I can only add support for this if original Yaru has this. It’s very much work to create themes for xfce and cinnamon, same for mate. 

I have to close this since this isn’t a real issue. If there’s support for other DE I’ll consider adding this to Yaru-Colors.

**Comment by OckhamOdyssey** [comment]
Hi. Yaru is already at Ubuntu MATE and Xubuntu. I suppose it has support to MATE and XFWM now?

**Comment by Jannomag** [comment]
The development is paused / stopped. I don't develop anything on Yaru-Colors anymore since Ubuntu has this feature built in
