### ISSUE TITLE
Working on pull request / having an issue with colors...

### ISSUE THREAD

**Issue by thoughtspacewebsites** [Jannomag/Yaru-Colors#93]
Hey Jannomag, so after my pull request the other day patching up symlinks and successfully managing to get my custom color working on my system, I got a bit enthralled by the project and decided to start working on building up the scripts some... The biggest thing that was a pain point for me in establishing custom colors (and you mentioned it took you days as well!) was getting the proper dependencies set up on my system before running `./theme-script.sh`. Well, I've been learning Docker recently, and one of the great things about it is that it lets you bundle up dependencies into a single, rebuildable, reusable format. I'm able to set up a Dockerfile, which defines all of the base OS / dependencies that my script is going to need in order to run, and then build that file up into a docker image, which can be run as a container (proper verbiage here). This container is almost like a virtual machine in a sense. What it allows me to do is get all the dependencies going in a basic, reusable script, which helps you to get set up faster on a new system to develop Yaru Colors further! I set up my container so that it has access to the cloned Yaru Colors repo on the user's computer, that way it can run the theme-script, and write files to the _compiled directory. 
It's all working quite nicely after hammering out a few bugs on my end, but the issue that I'm currently having is that the resulting theme files do not have properly assigned colors. The shell theme and the icons come out fine, but the base application theme itself uses a basic dark blue color instead of the assigned color. It is switching properly for dark / light / normal variants, but the highlight color seems to be the default and it isn't building up with the defined color. Any idea why this would be happening? I'm not seeing any noticable errors in my console when this happens.

**Comment by Jannomag** [comment]
Try checking the source files, like assets.svg for gtk themes. 
when the compiling script hits cancelled it won’t be able to recover the backup files so the files stay how they got already modified.
It’s a but with this script I couldn’t fix, yet - due the limitations of batch. 
while I’m writing this, an idea comes into my mind: add a head-script which executes the theme-script.sh with user variables and if the script failed it recovers the backup.
This should prevent such bugs - if your issue is like this
