### ISSUE TITLE
16 pixel icons are missing from Yaru-Cinnamon.

### ISSUE THREAD

**Issue by Initu-Castilhos** [Jannomag/Yaru-Colors#96]
The 16 pixel icon folder is missing from Yaru-Cinnamon.

**Comment by Jannomag** [comment]
I’m currently reworking everything because of many tiny changes Yaru devs made. It’s much work and I don’t have that much time.

I take a look over the icons when I’m done with the themes.
Thanks for the hint.

— issue stays open as reminder —
