### ISSUE TITLE
help to fix some things of the gtk theme

### ISSUE THREAD

**Issue by paulo8448** [Jannomag/Yaru-Colors#99]
hello all good i use unity as my main d.e and i would love to use your thema but i have some problems.
![WhatsApp Image 2021-05-02 at 20 36 16](https://user-images.githubusercontent.com/33562708/116831485-1585f500-ab86-11eb-9b96-80bcea9c1cf5.jpeg)
as you can see in the image above the background of the menus is white and leaves the icons invisible or very clear I would like to leave the background of the menus on the black panel and the white letters.
![0bd5e612-e5f2-41e0-8173-32acd191a1a3](https://user-images.githubusercontent.com/33562708/116831598-c4c2cc00-ab86-11eb-94e5-0985dcd93900.jpeg)
look I want to leave it like this. this theme there is the ambiance of the ubuntu old theme if you can help me by instructing me how to make this modification i would be very grateful. I await your response and congratulations on the theme gtk

**Comment by Jannomag** [comment]
Which distro and version are you using and what desktop runs on your system?
Did you try stock Yaru?
